
async function main() {
    console.log('Hello World!')
}

main().catch(err => console.log(err))